routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//
//Route::get('/backup',function(){
//    \Illuminate\Support\Facades\Artisan::call('backup:run');
//});
//
//Route::get('/login', function () {
//    return view('auth.login');
//});


Route::group(['prefix'=>'login','namespace'=>'Authentication'], function (){
    Route::group(['prefix'=>'user'],function () {
        Route::get('', 'AuthenticationController@index')->name('login');
        Route::post('auth', 'AuthenticationController@login')->name('user.login');

    });



});

Route::group(['prefix'=>'admin','namespace'=>'Dashboard'], function () {
    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('/home', 'DashboardController@index')->name('dashboard');
        Route::post('', 'DashboardController@logout')->name('logout');
        Route::get('/backup','DashboardController@backup')->name('backup');

    });

    Route::group(['prefix' => 'profile'], function () {
        Route::get('', 'ProfileController@index')->name('profile');
        Route::post('/update/{id}','ProfileController@update')->name('profile.update');
    });

    Route::group(['prefix' => 'settings'], function () {
        Route::get('', 'SettingsController@index')->name('settings');
        Route::post('/update','SettingsController@update')->name('settings.update');
    });

    Route::prefix('suggestion')->group(function (){
        Route::get('','SuggestionsController@index')->name('suggestion.index');
        Route::get('/show/{id}','SuggestionsController@show')->name('suggestion.show');
        Route::post('/{id}','SuggestionsController@destroy')->name('suggestion.destroy');
    });

    Route::prefix('category')->group(function (){
        Route::get('','CategoryController@index')->name('category.index');
        Route::get('/create','CategoryController@create')->name('category.create');
        Route::post('/store','CategoryController@store')->name('category.store');
        Route::get('/edit/{id}','CategoryController@edit')->name('category.edit');
        Route::post('/update/{id}','CategoryController@update')->name('category.update');
        Route::post('/{id}','CategoryController@destroy')->name('category.destroy');
        Route::post('/status/{id}', 'CategoryController@updateStatus')->name('category.status');
    });

    Route::prefix('subcategory')->group(function (){
        Route::get('','SubcategoryController@index')->name('subcategory.index');
        Route::get('/create','SubcategoryController@create')->name('subcategory.create');
        Route::post('/store','SubcategoryController@store')->name('subcategory.store');
        Route::get('/edit/{id}','SubcategoryController@edit')->name('subcategory.edit');
        Route::post('/update/{id}','SubcategoryController@update')->name('subcategory.update');
        Route::post('/{id}','SubcategoryController@destroy')->name('subcategory.destroy');
        Route::post('/status/{id}', 'SubcategoryController@updateStatus')->name('subcategory.status');
    });

    Route::prefix('user')->group(function (){
        Route::get('','UsersController@index')->name('user.index');
        Route::get('/create','UsersController@create')->name('user.create');
        Route::post('/store','UsersController@store')->name('user.store');
        Route::get('/details/{id}','UsersController@show')->name('user.show');
        Route::get('/edit/{id}','UsersController@edit')->name('user.edit');
        Route::post('/update/{id}','UsersController@update')->name('user.update');
        Route::post('/{id}','UsersController@destroy')->name('user.destroy');
        Route::post('/status/{id}', 'UsersController@updateStatus')->name('user.status');
    });

    Route::prefix('admins')->group(function (){
        Route::get('','AdminsController@index')->name('admin.index');
        Route::get('/create','AdminsController@create')->name('admin.create');
        Route::post('/store','AdminsController@store')->name('admin.store');
        Route::get('/edit/{id}','AdminsController@edit')->name('admin.edit');
        Route::post('/update/{id}','AdminsController@update')->name('admin.update');
        Route::post('/{id}','AdminsController@destroy')->name('admin.destroy');
        Route::post('/status/{id}', 'AdminsController@updateStatus')->name('admin.status');
    });

    Route::prefix('member')->group(function (){
        Route::get('','MembersController@index')->name('member.index');
        Route::get('/create','MembersController@create')->name('member.create');
        Route::post('/store','MembersController@store')->name('member.store');
        Route::get('/edit/{id}','MembersController@edit')->name('member.edit');
        Route::post('/update/{id}','MembersController@update')->name('member.update');
        Route::post('/{id}','MembersController@destroy')->name('member.destroy');
        Route::post('/status/{id}', 'MembersController@updateStatus')->name('member.status');
    });

    Route::prefix('technician')->group(function (){
        Route::get('','TechniciansController@index')->name('technician.index');
        Route::get('/create','TechniciansController@create')->name('technician.create');
        Route::post('/store','TechniciansController@store')->name('technician.store');
        Route::get('/edit/{id}','TechniciansController@edit')->name('technician.edit');
        Route::post('/update/{id}','TechniciansController@update')->name('technician.update');
        Route::post('/{id}','TechniciansController@destroy')->name('technician.destroy');
        Route::post('/status/{id}', 'TechniciansController@updateStatus')->name('technician.status');
        Route::post('/status/availability/{id}', 'TechniciansController@technicianAvailability')->name('technician.availability');
    });

    Route::prefix('orders')->group(function (){
        Route::get('','OrdersController@index')->name('orders.index');
        Route::get('/edit/{id}','OrdersController@edit')->name('orders.edit');
        Route::post('/update/{id}','OrdersController@update')->name('orders.update');
        Route::post('/{id}','OrdersController@destroy')->name('orders.destroy');
        Route::get('/details/{id}','OrdersController@show')->name('orders.show');
    });

    Route::prefix('reservations')->group(function (){
        Route::get('','ReservationsController@index')->name('reservations.index');
        Route::get('/{id}','ReservationsController@show')->name('reservations.show');
        Route::post('/{id}','ReservationsController@destroy')->name('reservations.destroy');
        Route::get('/invoice/{id}','ReservationsController@generatePdf')->name('reservations.invoice.show');
    });

    Route::prefix('sliders')->group(function (){
        Route::get('','SlidersController@index')->name('sliders.index');
        Route::get('/create','SlidersController@create')->name('sliders.create');
        Route::post('/store','SlidersController@store')->name('sliders.store');
        Route::get('/edit/{id}','SlidersController@edit')->name('sliders.edit');
        Route::post('/update/{id}','SlidersController@update')->name('sliders.update');
        Route::post('/{id}','SlidersController@destroy')->name('sliders.destroy');
        Route::post('/status/{id}', 'SlidersController@updateStatus')->name('sliders.status');
    });
});

app/Order.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table='orders';
    protected $fillable=['request_id', 'address', 'city_id', 'lat', 'lng', 
        'appartment', 'floor', 'total_price', 'additional_info', 'appointment', 'payment', 
        'status', 'month', 'day', 'time'];

    public function request()
    {
        return $this->belongsTo('App\Request');
    }

    public function city()
    {
        return $this->belongsTo('App\City');
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->toDateString();
    }
}

app/Suggestion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Suggestion extends Model
{
    protected $table='contacts';
    protected $fillable=['text'];
    public function user()
    {
        return $this->belongsTo('App\User','user_id');
    }
}

app/Http/Controllers/Api/technician/SuggestionsController.php
<?php

namespace App\Http\Controllers\Api\technician;

use App\Suggestion;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class SuggestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $jwt = ($request->hasHeader('jwt')) ? $request->header('jwt') : false;
        $user = User::where('jwt_token',$jwt)->first();

        $validator = Validator::make($request->all(), [
            'text' => 'required',
        ]);
        if ($validator->fails()) {
            return $this->sendError('Validation Error.', $validator->errors());
        }
        $suggestion=new Suggestion();
        $suggestion->user_id=$user->id;
        $suggestion->text = $request->text;
        $suggestion->save();
        $response=[
            'message'=>'suggestion created successfully',
            'status'=>200,
        ];
        return \Response::json($response,200);
        if (!$request->headers->has('jwt')){
            return response(401, 'check_jwt');
        }elseif (!$request->headers->has('lang')){
            return response(401, 'check_lang');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/user/SuggestionsController.php
<?php

namespace App\Http\Controllers\Api\user;

use App\Http\Controllers\Api\BaseController as BaseController;
use App\Suggestion;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class SuggestionsController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $jwt = ($request->hasHeader('jwt')) ? $request->header('jwt') : false;
        $user = User::where('jwt_token',$jwt)->first();

        $validator = Validator::make($request->all(), [
            'text' => 'required',
        ]);
        if ($validator->fails()) {
            return $this->sendError('Validation Error.', $validator->errors());
        }
        $suggestion=new Suggestion();
        $suggestion->user_id=$user->id;
        $suggestion->text = $request->text;
        $suggestion->save();
        $response=[
            'message'=>'suggestion created successfully',
            'status'=>200,
        ];
        return \Response::json($response,200);
        if (!$request->headers->has('jwt')){
            return response(401, 'check_jwt');
        }elseif (!$request->headers->has('lang')){
            return response(401, 'check_lang');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/SuggestionsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Suggestion;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SuggestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suggestions=Suggestion::all();
        return view('dashboard.views.suggestions.index',compact('suggestions'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $suggestion = Suggestion::find($id);
        $suggestion->view = 1;
        $suggestion->save();
        return view('dashboard.views.suggestions.show',compact('suggestion'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $suggestion = Suggestion::find($id);
        $suggestion->delete();
        return redirect()->back()->with('successMsg','Suggestion Successfully Delete');
    }
}

resources/views/dashboard/views/suggestions/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-left">
                            <h3>Suggestions DataTable</h3>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">Suggestions</li>
                                <li class="breadcrumb-item active">Suggestions Table</li>
                            </ol>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <!-- Zero Configuration  Starts-->
                <div class="col-sm-12">
                    @include('dashboard.partials.msg')
                    <div class="card">
                        <div class="card-header">
                            <h5>Suggestions Data</h5>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="display" id="basic-1">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>email</th>
                                        <th>suggestion</th>
                                        <th>Created At</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($suggestions as $key=>$suggestion)
                                        <tr>
                                            <td>{{ $key + 1 }}</td>
                                            <td>{{$suggestion->user->name}}</td>
                                            <td>{{$suggestion->user->email}}</td>
                                            <td>{{$suggestion->text}}</td>
                                            <td>{{$suggestion->created_at}}</td>
                                            <td>
                                                <a href="{{ route('suggestion.show',$suggestion->id) }}" class="btn btn-info">Details</a>

                                                <form id="delete-form-{{ $suggestion->id }}" action="{{ route('suggestion.destroy',$suggestion->id) }}" style="display: none;" method="POST">
                                                    @csrf
                                                </form>
                                                <button type="button" class="btn btn-danger" onclick="if(confirm('Are you sure? You want to delete this?')){
                                                        event.preventDefault();
                                                        document.getElementById('delete-form-{{ $suggestion->id }}').submit();
                                                        }else {
                                                        event.preventDefault();
                                                        }">Delete</button>
                                            </td>
                                        </tr>
                                    @endforeach


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Zero Configuration  Ends-->
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>





@endsection

resources/views/dashboard/views/suggestions/show.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-left">
                            <h3>Suggestion Details</h3>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">Suggestions </li>
                                <li class="breadcrumb-item active">Suggestion Details</li>
                            </ol>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="email-wrap">
                <div class="row">


                    <div class="col-xl-12 col-md-12">
                        <div class="email-right-aside">
                            <div class="card email-body radius-left">
                                <div class="pl-0">
                                    <div class="tab-content">
                                        <div class="tab-pane fade" id="pills-darkhome" role="tabpanel" aria-labelledby="pills-darkhome-tab">
                                            <div class="email-compose">
                                                <div class="email-top compose-border">
                                                    <div class="row">
                                                        <div class="col-sm-8 xl-50">
                                                            <h4 class="mb-0">New Message</h4>
                                                        </div>
                                                        <div class="col-sm-4 btn-middle xl-50">
                                                            <button class="btn btn-primary btn-block btn-mail text-center mb-0 mt-0" type="button"><i class="fa fa-paper-plane mr-2"></i> SEND</button>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="email-wrapper">
                                                    <form class="theme-form">
                                                        <div class="form-group">
                                                            <label class="col-form-label pt-0" for="exampleInputEmail1">To</label>
                                                            <input class="form-control" id="exampleInputEmail1" type="email">
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="exampleInputPassword1">Subject</label>
                                                            <input class="form-control" id="exampleInputPassword1" type="text">
                                                        </div>
                                                        <div class="form-group mb-0">
                                                            <label class="text-muted">Message</label>
                                                            <textarea id="text-box" name="text-box" cols="10" rows="2">                                                            </textarea>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade active show" id="pills-darkprofile" role="tabpanel" aria-labelledby="pills-darkprofile-tab">
                                            <div class="email-content">
                                                <div class="email-top">
                                                    <div class="row">
                                                        <div class="col-md-6 xl-100 col-sm-12">
                                                            <div class="media"><img class="mr-3 rounded-circle" src="../assets/images/user/user.png" alt="">
                                                                <div class="media-body">
                                                                    <h6>
                                                                        <img alt="" width="100px" src="{{$suggestion->user->image}}" class="media-object thumb-sm img-circle">
                                                                        <br>
                                                                        <small><span class="digits">{{$suggestion->user->name}} <span class="digits">
                                                                                    <br> {{$suggestion->created_at}}</span></span></small></h6>
                                                                    <p>{{$suggestion->user->email}}</p>
                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                                <div class="email-wrapper">
                                                    <p>{{$suggestion->text}}</p>
                                                </div>

                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        <div class="text-right">
                                                            <a style="
    margin-right: 20px;
" href="{{route('suggestion.index')}}" type="button" class="btn btn-primary waves-effect waves-light w-md m-b-30"><i class="mdi mdi-reply m-r-10"></i>Back</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>
@endsection